# Generated by Django 5.0.1 on 2024-01-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('mobile_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('constituency', models.CharField(max_length=30)),
                ('aadhaar_no', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Verification', 'Under Verification'), ('Approved', 'Approved')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voterid', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('mobile_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('constituency', models.CharField(max_length=30)),
                ('aadhaar_no', models.CharField(max_length=12)),
            ],
        ),
    ]
