# Generated by Django 5.0.1 on 2024-01-05 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='document_proof',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='applications',
            name='submitted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('Under Verification', 'Under Verification'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
    ]
