# Generated by Django 5.0.1 on 2024-01-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_applications_document_proof_applications_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='disable',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
