# Generated by Django 5.0.1 on 2024-01-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_applications_disable'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='apptype',
            field=models.CharField(default='apply', max_length=30),
        ),
    ]
